### ISSUE TITLE
Python 3.4: Type str doesn't support the buffer API

### ISSUE THREAD

**Issue by marcosguedes** [alesdotio/django-admin-shortcuts#33]
Running  `pip install django-admin-shortcuts` throws me this error. I suppose it has to do with the Python version as installing on a Python 3.6 environment doesn't raise issues.
Python version: 3.4
Package Version: 2.0.0

I've fixed it temporarily by installing version `1.2.7`

Can this be fixed?
Thank you

```
Collecting django-admin-shortcuts
  Downloading https://files.pythonhosted.org/packages/75/8b/9496dae0c9e08272c4ae73671ffeda14d29caf219bd6045d92a7dc265963/django-admin-shortcuts-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/django_admin_shortcuts.egg-info
    writing requirements to pip-egg-info/django_admin_shortcuts.egg-info/requires.txt
    writing pip-egg-info/django_admin_shortcuts.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ks80gcmj/django-admin-shortcuts/setup.py", line 28, in <module>
        keywords='',
      File "/projs/<project>/env/lib/python3.4/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/projs/<project>/env/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/projs/<project>/env/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/projs/<project>/env/lib/python3.4/site-packages/setuptools/dist.py", line 91, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/lib/python3.4/distutils/util.py", line 470, in rfc822_escape
        lines = header.split('\n')
    TypeError: Type str doesn't support the buffer API
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ks80gcmj/django-admin-shortcuts/
```

**Comment by marcosguedes** [comment]
Jumped the gun. It looks like it has nothing to do with django-admin-shortcuts and more with distutils. sorry!
